routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes(['verify' => true]);

Route::get('/questions/{question}/comments', 'QuestionCommentsController@index')->name('question-comments.index');
Route::post('/questions/{question}/comments', 'QuestionCommentsController@store')->name('question-comments.store');
Route::get('/answers/{answer}/comments', 'AnswerCommentsController@index')->name('answer-comments.index');
Route::post('/answers/{answer}/comments', 'AnswerCommentsController@store')->name('answer-comments.store');

Route::get('/questions', 'QuestionsController@index');
Route::get('/questions/{category?}', 'QuestionsController@index');
Route::get('/questions/create', 'QuestionsController@create')->name('questions.create');
Route::get('/questions/{category}/{question}/{slug?}', 'QuestionsController@show')->name('questions.show');
Route::post('/questions', 'QuestionsController@store');
Route::post('/questions/{question}/answers', 'AnswersController@store');
Route::post('/questions/{question}/published-questions', 'PublishedQuestionsController@store')->name('published-questions.store');

Route::post('/questions/{question}/subscriptions', 'SubscribeQuestionsController@store')->name('subscribe-questions.store');
Route::delete('/questions/{question}/subscriptions', 'SubscribeQuestionsController@destroy')->name('subscribe-questions.destroy');


Route::delete('/answers/{answer}', 'AnswersController@destroy')->name('answers.destroy');
Route::post('/answers/{answer}/best', 'BestAnswersController@store')->name('best-answers.store');
Route::post('/answers/{answer}/up-votes', 'AnswerUpVotesController@store')->name('answer-up-votes.store');
Route::delete('/answers/{answer}/up-votes', 'AnswerUpVotesController@destroy')->name('answer-up-votes.destroy');
Route::post('/answers/{answer}/down-votes', 'AnswerDownVotesController@store')->name('answer-down-votes.store');
Route::delete('/answers/{answer}/down-votes', 'AnswerDownVotesController@destroy')->name('answer-down-votes.destroy');
Route::post('/answers/{answer}/comments', 'AnswerCommentsController@store')->name('answer-comments.store');

Route::post("/questions/{question}/up-votes", 'QuestionUpVotesController@store')->name('question-up-votes.store');
Route::delete('/questions/{question}/up-votes', "QuestionUpVotesController@destroy")->name('question-up-votes.destroy');
Route::post('/questions/{question}/down-votes', 'QuestionDownVotesController@store')->name('question-down-votes.store');
Route::delete('/questions/{question}/down-votes', 'QuestionDownVotesController@destroy')->name('question-down-votes.destroy');
Route::post('/questions/{question}/comments', 'QuestionCommentsController@store')->name('question-comments.store');

Route::get('/drafts', 'DraftsController@index')->name('drafts.index');

// 点赞评论
Route::post('/comments/{comment}/up-votes', 'CommentUpVotesController@store')->name('comment-up-votes.store');
// 取消点赞评论
Route::delete('/comments/{comment}/up-votes', 'CommentUpVotesController@destroy')->name('comments-up-votes.destroy');

Route::post('/comments/{comment}/down-votes', 'CommentDownVotesController@store')->name('comment-down-votes.store');
Route::delete('/comments/{comment}/down-votes', 'CommentDownVotesController@destroy')->name('comment-down-votes.destroy');

Route::post('/users/{user}/avatar', 'UserAvatarsController@store')->name('user-avatars.store');
Route::get('/profiles/{user}', 'ProfilesController@show')->name('users.show');
Route::get('/notifications', 'UserNotificationsController@index')->name('user-notifications.index');

app/Models/Question.php
<?php

namespace App\Models;

use App\Notifications\QuestionWasUpdated;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    use \App\Models\Traits\VoteTrait;
    use \App\Models\Traits\CommentTrait;
    use \App\Models\Traits\RecordActivityTrait;

    protected $table = 'questions';

    protected $guarded = [
        'id',
    ];

    protected $with = [
        'category',
    ];

    protected $appends = [
        'upVotesCount',
        'downVotesCount',
        'subscriptionsCount',
        'commentsCount',
    ];

    public function answers()
    {
        return $this->hasMany(Answer::class);
    }

    public function creator()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    /**
     *
     * @param $query
     * @return mixed
     */
    public function scopePublished($query)
    {
        return $query->whereNotNull('published_at');
    }

    public function scopeDrafts($query, $userId)
    {
        return $query->where(['user_id' => $userId])->whereNull('published_at');
    }

    public function scopeFilter($query, $filters)
    {
        return $filters->apply($query);
    }

    public function markAsBestAnswer($answer)
    {
        $this->update([
            'best_answer_id' => $answer->id,
        ]);
    }

    /**
     * 发布问题
     */
    public function publish()
    {
        $this->update([
            'published_at' => now(),
        ]);
    }

    public function invitedUsers()
    {
        preg_match_all('/@([^\s.]+)/', $this->content, $matches);

        return $matches[1];
    }

    public function subscriptions()
    {
        return $this->hasMany(Subscription::class);
    }

    public function subscribe($userId)
    {
        $this->subscriptions()->create([
            'user_id' => $userId,
        ]);

        return $this;
    }

    public function unsubscribe($userId)
    {
        $this->subscriptions()->where([
            'user_id' => $userId,
        ])->delete();

        return $this;
    }

    public function addAnswer($answer)
    {
        $answer = $this->answers()->create($answer);

        $this->subscriptions()
            ->where('user_id', '!=', $answer->user_id)
            ->each(function ($item) use ($answer){
                $item->user->notify(new QuestionWasUpdated($this, $answer));
            });

        /*
        $this->subscriptions
            ->where('user_id', '!=', $answer->user_id)
            ->each
            ->notify($answer);
        */
        return $answer;
    }

    public function isSubscribedTo($user)
    {
        if (! $user) {
            return false;
        }

        return $this->subscriptions()
            ->where('user_id', $user->id)
            ->exists();
    }

    public function getSubscriptionsCountAttribute()
    {
        return $this->subscriptions->count();
    }

    public function path()
    {
        return $this->slug ? "/questions/{$this->category->slug}/{$this->id}/{$this->slug}" : "/questions/{$this->category->slug}/{$this->id}";
    }
}

app/Models/Traits/CommentTrait.php
<?php

namespace App\Models\Traits;

use App\Events\PostComment;

trait CommentTrait
{
    public function comment($content, $user)
    {
        $comment = $this->comments()->create([
            'user_id' => $user->id,
            'content' => $content,
        ]);

        event(new PostComment($comment));

        return $comment;
    }

    public function comments()
    {
        return $this->morphMany(\App\Models\Comment::class, 'commented');
    }

    public function getCommentsCountAttribute()
    {
        return $this->comments->count();
    }

    public function getCommentEndpointAttribute()
    {
        return '/' . $this->table . '/' . $this->id . '/comments';
    }
}

app/Http/Controllers/QuestionsController.php
<?php

namespace App\Http\Controllers;

use App\Filters\QuestionFilter;
use App\Models\Category;
use App\Models\Question;
use App\Models\User;
use Auth;
use Illuminate\Http\Request;

class QuestionsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->except(['show', 'index']);

        $this->middleware('must-verify-email')->except(['index', 'show']);
    }

    public function index(Category $category, QuestionFilter $filters, User $user)
    {
        if ($category->exists) {
            $questions = Question::published()->where('category_id', $category->id);
        } else {
            $questions = Question::published();
        }

        $questions = $questions->filter($filters)->paginate(20);

        array_map(function (&$item) {
            return $this->appendAttribute($item);
        }, $questions->items());

        $activeUsers = $user->getActiveUsers();

        return view('questions.index', [
            'questions' => $questions,
            'activeUsers' => $activeUsers,
        ]);
    }

    public function create(Question $question)
    {
        $categories = Category::all();

        return view('questions.create', [
            'question' => $question,
            'categories' => $categories,
        ]);
    }

    public function show($category, $questionId)
    {
        $question = Question::published()->findOrFail($questionId);

        $answers = $question->answers()->paginate(20);

        array_map(function (&$item) {
            return $this->appendVotedAttribute($item);
        }, $answers->items());

        return view('questions.show', [
            'question' => $question,
            'answers' => $answers,
        ]);
    }

    public function store()
    {
        $this->validate(request(), [
            'title' => 'required',
            'content' => 'required',
            'category_id' => 'required|exists:categories,id',
        ]);

        $question = Question::create([
            'user_id' => auth()->id(),
            'category_id' => request('category_id'),
            'title' => request('title'),
            'content' => request('content'),
        ]);

        return redirect("/drafts")->with('flash', '创建成功.');
    }

    protected function appendAttribute($item)
    {
        $user = Auth::user();

        $item->isVotedUp = $item->isVotedUp($user);
        $item->isVotedDown = $item->isVotedDown($user);
        $item->isSubscribedTo = $item->isSubscribedTo($user);

        return $item;
    }
}

resources/views/questions/_answer.blade.php
<answer :attributes="{{ $answer }}" inline-template>
    <li class="media" name="answer{{ $answer->id }}" id="answer{{ $answer->id }}">
        <div class="media-left">
            <a href="#">
                <img class="media-object img-thumbnail mr-3" alt="{{ $answer->owner->name }}" src="{{ $answer->owner->userAvatar }}" style="width:48px;height:48px;" />
            </a>
        </div>

        <div class="media-body">
            <div class="media-heading mt-0 mb-1 text-secondary">
                <a href="/profiles/{{ $answer->owner->id }}" title="{{ $answer->owner->name }}">
                    {{ $answer->owner->name }}
                </a>
                <span class="text-secondary"> • </span>
                <span class="meta text-secondary" title="{{ $answer->created_at }}">{{ $answer->created_at->diffForHumans() }}</span>

                <a class="float-right" >
                    @if($answer->isBest())
                        <button class="btn btn-warning btn-sm"><i class="fa fa-check"></i> 最佳答案</button>
                    @else
                        @can('update', $question)
                            <form action="/answers/{{ $answer->id }}/best" method="POST" accept-charset="UTF-8">
                                {{ csrf_field() }}
                                <button type="submit" class="btn btn-primary btn-sm">设为最佳</button>
                            </form>
                        @endcan

                        @can('delete', $answer)
                            <form action="/answers/{{ $answer->id }}" method="POST" accept-charset="UTF-8">
                                {{ method_field("DELETE") }}
                                {{ csrf_field() }}
                                <button type="submit" class="btn btn-primary btn-sm">删除</button>
                            </form>
                        @endcan
                    @endif
                </a>

            </div>

            <div class="answer-content text-secondary">
                <p v-html="content"></p>
            </div>

            <small class="media-body meta text-secondary">
                <a class="text-secondary" role="button" href="#" data-toggle="modal" data-target="#modal{{$answer->id}}">
                    <i class="fa fa-comments"></i>
                    {{ $answer->comments_count }} 个评论
                </a>

                <div class="modal fade" id="modal{{$answer->id}}" tabindex="-1" role="dialog" aria-labelledby="modal{{$answer->id}}" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-scrollable" >
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title" id="modal{{$answer->id}}">
                                    评论列表
                                </h4>
                            </div>
                            <div class="modal-body">
                                <comments :data="{{ $answer->comments }}" :subject="{{ $answer }}"></comments>
                            </div>
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div>
                <span> • </span>

                <answer-affect :answer="{{ $answer }}" v-if="signedIn"></answer-affect>
            </small>
        </div>
    </li>
</answer>

resources/views/questions/_answer_box.blade.php
@include('shared._error')

<div class="answer-box">
    <form action="/questions/{{ $question->id }}/answers" method="POST" accept-charset="UTF-8">
        {{ csrf_field() }}
        <div class="form-group">
            <textarea class="form-control" rows="3" placeholder="让我来回答~" name="content"></textarea>
        </div>
        <button type="submit" class="btn btn-primary btn-sm">
            <i class="fa fa-share mr-1"></i> 发布回答
        </button>
    </form>
</div>

resources/views/questions/_answer_list.blade.php
<ul class="list-unstyled">
    @foreach ($answers as $index => $answer)
        @include('questions._answer')
        @if (! $loop->last)
            <hr />
        @endif
    @endforeach
</ul>

resources/views/questions/_question.blade.php
<question :attributes="{{ $question }}" inline-template>
    <li class="media">
        <div class="media-body">
            <div class="media-heading mt-1 mb-1">
                <a class="text-dark" href="{{ route('questions.show', [$question->category, $question->id, $question->slug]) }}" title="{{ $question->title }}">
                    {{ $question->title }}
                </a>

                <a class="float-right text-muted">
                    <i class="far fa-clock"></i>
                    <span class="timeago">{{ $question->updated_at->diffForHumans() }}</span>
                </a>
            </div>

            <small class="media-body meta text-muted mt-2">
                <question-affect :question="{{ $question }}" :display="false"></question-affect>
            </small>
        </div>
    </li>
</question>

resources/views/questions/_sidebar.blade.php
<div class="card">
    <div class="card-body">
        <a href="/questions/create" class="btn ben-primary btn-block" aria-label="Left Align">
            <i class="fas fa-pencil-alt mr-2"></i>提个问题?
        </a>
    </div>
</div>

@if (count($activeUsers))
    <div class="card mt-4">
        <div class="card-body active-users pt-2">
            <div class="text-center mt-1 mb-0 text-muted">活跃用户</div>
            <hr class="mt-2">
            @foreach ($activeUsers as $activeUser)
                <a class="media mt-2" href="{{ route('users.show', $activeUser->id) }}">
                    <div class="media-left media-middle mr-2 ml-1">
                        <img src="{{ $activeUser->userAvatar }}" width="24px" height="24px" class="media-object">
                    </div>
                    <div class="media-body">
                        <small class="media-heading text-secondary">{{ $activeUser->name }}</small>
                    </div>
                </a>
            @endforeach
        </div>
    </div>
@endif

resources/views/questions/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="col-md-10 offset-md-1">
            <div class="card">
                <div class="card-body">
                    <h2 class="">
                        <i class="far fa-edit"></i>
                        提个问题
                    </h2>

                    <hr />

                    <form action="/questions" method="POST" accept-charset="UTF-8">
                        {{ csrf_field() }}

                        @include('shared._error')

                        <div class="form-group">
                            <input class="form-control" type="text" name="title" value="{{ old('title', $question->title) }}" placeholder="请填写标题" required dusk="question-title" />
                        </div>

                        <div class="form-group">
                            <select class="form-control" name="category_id" required dusk="question-category">
                                <option value="" hidden disabled selected>请选择分类</option>
                                @foreach ($categories as $value)
                                    <option value="{{ $value->id }}">{{ $value->name }}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <textarea name="content" class="form-control" id="editor" rows="6" placeholder="请填入至少 3 个字符的内容" required dusk="question-content">{{ old('content', $question->content) }}</textarea>
                        </div>

                        <div class="well well-sm">
                            <button type="submit" class="btn btn-primary" dusk="question-submit">
                                <i class="far fa-save mr-2" aria-hidden="true"></i> 保存
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/questions/index.blade.php
@extends('layouts.app')

@section('title', '问题列表')

@section('content')
<div class="row mb-5">
    <div class="col-lg-9 col-md-9 topic-list">
        <div class="card">
            <div class="card-body">
                {{-- 问题列表 --}}
                @if (count($questions))
                    <ul class="list-unstyled">
                        @foreach ($questions as $question)
                            @include('questions._question')
                            @if (! $loop->last)
                                <hr />
                            @endif
                        @endforeach
                    </ul>

                @else
                    <div class="empty-block">暂无数据 ~_~ </div>
                @endif
                {{-- 分页 --}}
                <div class="mt-5">
                    {!! $questions->appends(Request::except('page'))->render() !!}
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-3 col-md-3 sidebar">
        @include('questions._sidebar')
    </div>
</div>
@stop

resources/views/questions/show.blade.php
@extends('layouts.app')

@section('title', $question->title)

@section('content')
    <question :attributes="{{ $question }}" :displaySubscription="true" inline-template>
        <div class="row">
            <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12 question-content">
                <div class="card">
                    <div class="card-body">
                        <h1 class="mt-3 mb-3">
                            {{ $question->title }}
                        </h1>
                        <div class="question-body mt-4 mb-4">
                            {!! $question->content !!}
                        </div>

                        <p class="media-body meta text-secondary">
                            <question-affect :question="{{ $question }}" :display="true"></question-affect>
                        </p>
                    </div>
                </div>

                {{-- 答案列表 --}}
                <div class="card question-reply mt-4">
                    @includeWhen(Auth::check(), 'questions._answer_box', ['question' => $question])

                    @if (count($answers) > 0)
                        <div class="card-body">
                            @include('questions._answer_list', ['answers' => $answers])
                            <div class="mt-5">
                                {!! $answers->appends(Request::except('page'))->render() !!}
                            </div>
                        </div>
                    @else
                        <div class="empty-block">暂时没有任何人回答~ </div>
                    @endif
                </div>
            </div>

            <div class="col-lg-3 col-md-3 hidden-sm hidden-xs author-info">
                <div class="card">
                    <div class="card-body">
                        <div class="text-center">
                            提问者: {{ $question->creator->name }}
                        </div>
                        <hr />
                        <div class="media">
                            <div align="center">
                                <a href="/profiles/{{ $question->creator->id }}">
                                    <img class="thumbnail img-fluid" src="{{ $question->creator->userAvatar }}" width="300px" height="300px" />
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </question>
@stop